fw/b: Add support for allowing/disallowing apps on cellular, vpn and wifi networks
Dynamically add/remove apps from restricted networking mode's allowlist based on policy and network transport changes

Change-Id: I526d0058cda71a9e93046d116c0d79093390a85b
(cherry picked from commit b6f790a29d76591b2bdb45566162d0ae1e1b3243)

* Check active network per UID
* Listen to changes in all networks
* Limit backend calls during network capability changes to transport changes
* Allow traffic over VPN networks if policy does not restrict it even if other transports are present

Also includes:
commit aae3a459697158e40a466bb2f86726bb0e82aec0
Author:     Chirayu Desai <chirayudesai1@gmail.com>
AuthorDate: Sat Dec 18 00:51:54 2021 +0530

    hasRestrictedModeAccess: Clear calling identity when checking network capabilities

    * This code ends up being called from Datura, the firewall app,
      which would fail with:
    java.lang.SecurityException: Package android does not belong to 10139
       at android.net.NetworkPolicyManager.removeUidPolicy(NetworkPolicyManager.java:352)
       at org.calyxos.datura.settings.SettingsManager.setAppRestriction(SettingsManager.java:108)
    Caused by: android.os.RemoteException: Remote stack trace:
       at android.app.AppOpsManager.checkPackage(AppOpsManager.java:8552)
       at com.android.server.ConnectivityService.getNetworkCapabilities(ConnectivityService.java:2042)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1563)
       at com.android.server.net.NetworkPolicyManagerService.hasRestrictedModeAccess(NetworkPolicyManagerService.java:4133)
       at com.android.server.net.NetworkPolicyManagerService.getNewRestrictedModeUidRule(NetworkPolicyManagerService.java:4116)
    Package android does not belong to 10139
      where 10139 is the uid of the firewall app
    * This should be safe since we're only checking the capabilities here,
      and not actually returning anything anywhere - just a boolean

    Change-Id: Ia0b5790be19ad5aece0d30ae8e1a465f45f4fed6

Change-Id: I0d719bb7c7f04a493a4ddefa8e6154ef4159abd0