Let Firewall app uid call setFirewallUidRule
* Datura, the firewall app, would fail without this:
java.lang.SecurityException: Only available to AID_SYSTEM
   at android.net.NetworkPolicyManager.removeUidPolicy(NetworkPolicyManager.java:352)
   at org.calyxos.datura.settings.SettingsManager.setAppRestriction(SettingsManager.java:108)
Caused by: android.os.RemoteException: Remote stack trace:
   at com.android.server.NetworkManagementService.enforceSystemUid(NetworkManagementService.java:1670)
   at com.android.server.NetworkManagementService.setFirewallUidRule(NetworkManagementService.java:1578)
   at com.android.server.net.NetworkPolicyManagerService.setUidFirewallRule(NetworkPolicyManagerService.java:5566)
   at com.android.server.net.NetworkPolicyManagerService.updateRestrictedModeForUidUL(NetworkPolicyManagerService.java:4162)
   at com.android.server.net.NetworkPolicyManagerService.setUidPolicyUncheckedUL(NetworkPolicyManagerService.java:2976)
Only available to AID_SYSTEM
* This should be safe since we're only modifying this one function,
  and the datura uid would only be available to 'platform' apps,
  so any third party apps would not be able to get it.

Change-Id: I642e2f370d5a3d65d1c3d205d7c668a5530a8fb4